version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: copiou-papelaria-container
    environment:
      POSTGRES_DB: 'copiou_papelaria'
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always