spring:
  application:
    name: copiou-papelaria-api

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

  web:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS_URL}
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      exposed-headers: "Authorization"
      allow-credentials: true
      max-age: 3600

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

copioupapelaria:
  security:
    secret: ${SECRET}